version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    restart: always
    env_file: .env.db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    image: "backend"
    restart: always
    build:
      context: .
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/home/app/web
      - /var/volumes/static_volume:/home/app/web/staticfiles
      - /var/volumes/media_volume:/home/app/web/media
    command: [ "sh","./start" ]
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - /var/volumes/static_volume:/home/app/web/staticfiles
      - /var/volumes/media_volume:/home/app/web/media
    depends_on:
      - web

volumes:
  postgres_data:
